language: csharp
mono: none
dotnet: 2.1.4
script:
 - cd $TRAVIS_BUILD_DIR/FMark/FMarkCLI
 - dotnet build -v n
 - dotnet run --no-build -- -t
 - cd $TRAVIS_BUILD_DIR/FMark/FMarkFable
 - dotnet restore
 - dotnet fable yarn-build
