language: csharp
mono: none
dotnet: 2.1.4
script:
  - mozroots --import
  - cd $TRAVIS_BUILD_DIR/FMark/src/FMarkCLI
  - dotnet build -v n
  - dotnet run --no-build -- -t
  - cd $TRAVIS_BUILD_DIR/FMark/src/FMarkFable
  - dotnet restore
  - dotnet fable yarn-build
install:
  - sudo apt-get -qq update
  - sudo apt-get install -y mono-complete
