FROM fsharp

# Taken from  https://code.visualstudio.com/docs/setup/linux
RUN apt-get update && apt-get install -y curl gpg apt-utils
RUN curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg
RUN install -o root -g root -m 644 packages.microsoft.gpg /usr/share/keyrings/
RUN sh -c 'echo "deb [arch=amd64 signed-by=/usr/share/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'
RUN apt-get install -y apt-transport-https
RUN apt-get update
RUN apt-get install -y code # or code-insiders

# RUN apt update && apt install software-properties-common apt-transport-https wget
# RUN wget -q https://packages.microsoft.com/keys/microsoft.asc -O- | sudo apt-key add -


# RUN apt-get update && apt-get install snapd && snap install --classic code
# RUN apt-get update && apt-get install snapd && snap install --classic code
