type Token =
    | WORD of string | MISCCHAR of string | NUMBER of string | SPACE | TAB
    | DOT | POUND | PIPE | COLON | EQUAL | MINUS | PLUS | ASTERISK | DASTERISK
    | TASTERISK | UNDERSCORE | DUNDERSCORE | TUNDERSCORE | TILDE | DTILDE
    | TTILDE | LSBRA | RSBRA | LBRA | RBRA | BSLASH | LABRA | RABRA | LCBRA
    | RCBRA | BACKTICK | TBACKTICK
